# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Dance Cloud
email: dancecloud@cndb.ro
description: > # this means to ignore newlines until "baseurl:"
  Platforma online a dansului contemporan românesc
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://dancecloud.ro" # the base hostname & protocol for your site

# Page generation
page_gen-dirs: true # uncomment, if you prefer to generate named folders
page_gen:
  - data: 'azi-artisti'
    template: 'artist'
    name: 'nume'
    dir: 'azi/artisti'

  - data: 'azi-organizatii'
    template: 'organisation'
    name: 'denumire'
    dir: 'azi/organizatii'

  - data: 'azi-spectacole'
    template: 'show'
    name: 'titlu'
    dir: 'azi/spectacole'

  - data: 'azi-filmeemisiuni'
    template: 'film'
    name: 'titlu'
    dir: 'azi/filme-emisiuni'

  - data: 'azi-publicatii'
    template: 'publication'
    name: 'titlu'
    dir: 'azi/publicatii'

  - data: 'azi-festivaluri'
    template: 'festival'
    name: 'titlu'
    dir: 'azi/festivaluri'

  - data: 'ieri-coregrafidansatori'
    template: 'choreograph'
    name: 'nume'
    dir: 'ieri/coregrafidansatori'

  - data: 'ieri-colective'
    template: 'collective'
    name: 'nume'
    dir: 'ieri/colective'

  - data: 'ieri-organizatii'
    template: 'old_organisation'
    name: 'nume'
    dir: 'ieri/organizatii'

  - data: 'ieri-oameniaidansului'
    template: 'old_artist'
    name: 'nume'
    dir: 'ieri/oameni-ai-dansului'

  - data: 'maine-evenimente'
    template: 'maine-evenimente'
    name: 'nume'
    dir: 'maine'

# Build settings
markdown: kramdown
permalink: none
user: devel
exclude: ['sandbox', 'fabfile.py', '*.sh', 'INSTRUCTIONS.md', 'README.me']

defaults:
  - scope:
      path: "assets/images"
    values:
      image: true
