# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Dance Cloud
email: dancecloud@cndb.ro
description: > # this means to ignore newlines until "baseurl:"
  Platforma online a dansului contemporan românesc
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://dancecloud.ro" # the base hostname & protocol for your site
github_username:  nico4

# Build settings
markdown: kramdown
permalink: none
user: devel
exclude: [sandbox, fabfile.py]

defaults:
  - scope:
      path: "assets/images"
    values:
      image: true
