# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Dance Cloud
email: dancecloud@cndb.ro
description: > # this means to ignore newlines until "baseurl:"
  Platforma online a dansului contemporan românesc
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://alfa.dancecloud.ro" # the base hostname & protocol for your site

# Page generation
page_gen-dirs: true # uncomment, if you prefer to generate named folders
page_gen:
  - data: 'artists'
    template: 'artist'
    name: 'nume'
    dir: 'azi/artisti'

  - data: 'organisations'
    template: 'organisation'
    name: 'id'
    dir: 'azi/organizatii'

  - data: 'shows'
    template: 'show'
    name: 'id'
    dir: 'azi/spectacole'

  - data: 'films'
    template: 'film'
    name: 'id'
    dir: 'azi/filme'

  - data: 'publications'
    template: 'publication'
    name: 'id'
    dir: 'azi/publicatii'

  - data: 'festivals'
    template: 'festival'
    name: 'id'
    dir: 'azi/festivale'

  - data: 'choreographers'
    template: 'choreograph'
    name: 'nume'
    dir: 'ieri/coregrafi'

  - data: 'collective'
    template: 'collective'
    name: 'nume'
    dir: 'ieri/colective'

  - data: 'old_organisations'
    template: 'old_organisation'
    name: 'nume'
    dir: 'ieri/organizatii'

  - data: 'old_artists'
    template: 'old_artist'
    name: 'nume'
    dir: 'ieri/oameni_ai_dansului'

# Build settings
markdown: kramdown
permalink: none
user: devel
exclude: ['sandbox', 'fabfile.py']

defaults:
  - scope:
      path: "assets/images"
    values:
      image: true
