# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: DanceCloud.ro
email: dancecloud@cndb.ro
description: > # this means to ignore newlines until "baseurl:"
  Platforma dansului contemporan românesc
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://dancecloud.ro" # the base hostname & protocol for your site


# Plugins
# Data Pages Generator, https://github.com/avillafiorita/jekyll-datapage_gen/

# Page generation
page_gen-dirs: true # uncomment, if you prefer to generate named folders
page_gen:
  - data: 'azi-artisti'
    template: 'azi-artisti'
    name: 'nume'
    dir: 'azi/artisti'

  - data: 'azi-organizatii'
    template: 'azi-organizatii'
    name: 'denumire'
    dir: 'azi/organizatii'

  - data: 'azi-spectacole'
    template: 'azi-spectacole'
    name: 'titlu'
    dir: 'azi/spectacole'

  - data: 'azi-filmeemisiuni'
    template: 'azi-filmeemisiuni'
    name: 'titlu'
    dir: 'azi/filme-emisiuni'

  - data: 'azi-publicatii'
    template: 'azi-publicatii'
    name: 'titlu'
    dir: 'azi/publicatii'

  - data: 'azi-festivaluri'
    template: 'azi-festivaluri'
    name: 'titlu'
    dir: 'azi/festivaluri'

  - data: 'ieri-coregrafidansatori'
    template: 'ieri-coregrafidansatori'
    name: 'nume'
    dir: 'ieri/coregrafidansatori'

  - data: 'ieri-colective'
    template: 'ieri-colective'
    name: 'nume'
    dir: 'ieri/colective'

  - data: 'ieri-organizatii'
    template: 'ieri-organizatii'
    name: 'nume'
    dir: 'ieri/organizatii'

  - data: 'ieri-oameniaidansului'
    template: 'ieri-oameniaidansului'
    name: 'nume'
    dir: 'ieri/oameni-ai-dansului'

  - data: 'maine-evenimente'
    template: 'maine-evenimente'
    name: 'titlu'
    dir: 'maine'

# Build settings
markdown: kramdown
permalink: none
user: devel
exclude: ['sandbox', 'fabfile.py', '*.sh', 'INSTRUCTIONS.md', 'README.me']

defaults:
  - scope:
      path: "assets/photos"
    values:
      image: true
      gallery: true

# Vimeo
# use __videoID__ to replace ID

vimeo:
  access_token: 19a4e5cfeca40523b60d868d10d3a8e5
  videoURL: "http://vimeo.com/api/v2/video/__videoID__.json"
  channelURL: "http://vimeo.com/api/v2/channels/__channel__.json"
